### ISSUE TITLE
Hi, this project is nice, can you create a windows 64 bit codeblocks builds?

### ISSUE THREAD

**Issue by asmwarrior** [zxunge/x86-codeblocks-builds#1]
I think a lot of people are using 64 bit windows system, so I'm asking if it is possible to build a 64 bit version?

Thanks.

BTW: I see that in the yml file, you have try to download the wx library from the msys2, but from the build.sh file, I see you need to build the wx library yourself, so which wx library did you use for building the C::B?

**Comment by zxunge** [comment]
Those code for building a new wxwidgets is not used now, as I think using the wxwidgets built by msys2 is more convenient. They're commented; maybe they will be enabled in the future. 
<br /> I.will try 64-bit builds.

**Comment by asmwarrior** [comment]
> Those code for building a new wxwidgets is not used now, as I think using the wxwidgets built by msys2 is more convenient. 

OK.

> They're commented; maybe they will be enabled in the future. I.will try 64-bit builds.

Nice, thanks. Once you have done that job, I will try to learn myself.

I have posted a message in C::B forum, see here:

[build bot in the github, I see one nice project](https://forums.codeblocks.org/index.php/topic,25856.new.html#new)

**Comment by zxunge** [comment]
Hi, I have already build a 64b version successfully.
Please download the artifact at [main64 workflow](https://github.com/zxunge/i686-codeblocks-builds/actions/runs/10429187222)

**Comment by zxunge** [comment]
> I have posted a message in C::B forum, see here:
> 
> [build bot in the github, I see one nice project](https://forums.codeblocks.org/index.php/topic,25856.new.html#new)

In fact, I'm just the user _GritClef_ in the C::B forums :blush: !

**Comment by asmwarrior** [comment]
OK, so the discussion can goes to the C::B forum.

Once you have successfully solved the build issue, I think you can change the project name from "i686-codeblocks-builds" to something like “x86-codeblocks-builds”, because both 32bit and 64 bit C::B are supported.
