### ISSUE TITLE
Why MSYS2?

### ISSUE THREAD

**Issue by MichaelAgarkov** [zxunge/x86-codeblocks-builds#2]
Hello, I'd like to ask why does the script build C::B for use in MSYS2 when it can be compiled to be standalone and work without MSYS2. Is there a reason to that?

**Comment by asmwarrior** [comment]
I think the reason to use msys2 is that it has many build in libraries for the G++ compiler, for example, it has boost library(need to build one C::B plugin)

**Comment by zxunge** [comment]
It's more complex if you don't use msys2. It's not easy to build those cb projects using cb through cli in github action.
